openapi: 3.0.0
info:
  version: '1.0.0'
  title: openrecipes
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: |
    # Openrecipes
    This is the API doc of https://github.com/oliverdozsa/openrecipes.
paths:
  '/ingredientnames':
    get:
      summary: Query a page of ingredient names
      parameters:
        - name: languageId
          in: query
          schema:
            type: integer
          required: true
        - name: nameLike
          in: query
          schema:
            type: string
            minLength: 2
          required: false
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 50
            default: 25
      responses:
        '200':
          description: Page of ingredient names.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientNamePage'
              example:
                totalCount: 2
                items: [{ingredientId: 1, name: 'Lemon'}, {ingredientId: 2, name: 'Orange'}]
        '400':
          description: Map of error keys to error messages
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
              example:
                "languagedId": ["Missing field", "Another problem"]
                "": ["Some global errors", "And some more"]

  '/sourcepages':
    get:
      summary: All source pages
      responses:
        '200':
          description: List of source pages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourcePageList'
              example:
                totalCount: 2
                items: [{id: 1, name: "TheRecipeWebSite"}, {id: 2, name: "Cooking.com"}]

components:
  schemas:
    IngredientName:
      description: An ingredient name.
      type: object
      properties:
        id:
          description: ID
          type: integer
        name:
          description: The name
          type: string
    IngredientNamePage:
      description: Page of ingredient names.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/IngredientName'
        totalCount:
          type: integer
    SourcePageList:
      description: List of source pages.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SourcePage'
        totalCount:
          type: integer
    SourcePage:
      description: A source page.
      type: object
      properties:
        id:
          description: ID
          type: integer
        name:
          description: The name of the source page.
          type: string
    RecipePage:
      description: Page of recipes.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Recipe'
        totalCount:
          type: integer
    Recipe:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        numofings:
          type: integer
        sourcePage:
          $ref: '#/components/schemas/SourcePage'
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientName'
